// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeUkqd8X9BBC1F-UtihwhK0HJ7cCX5W2E',
    appId: '1:100007027162:web:f35ab7581ed40ffe6a20e3',
    messagingSenderId: '100007027162',
    projectId: 'doctify-9786a',
    authDomain: 'doctify-9786a.firebaseapp.com',
    storageBucket: 'doctify-9786a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9f-poWYE7rnf08rRLWc7u6g8XlbFROyI',
    appId: '1:100007027162:android:123a9f8bc55a08a26a20e3',
    messagingSenderId: '100007027162',
    projectId: 'doctify-9786a',
    storageBucket: 'doctify-9786a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq5BLGGofLpVyfLn-6HaaZV7X557PJ1s8',
    appId: '1:100007027162:ios:e89bc0fe490ae7a86a20e3',
    messagingSenderId: '100007027162',
    projectId: 'doctify-9786a',
    storageBucket: 'doctify-9786a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq5BLGGofLpVyfLn-6HaaZV7X557PJ1s8',
    appId: '1:100007027162:ios:e89bc0fe490ae7a86a20e3',
    messagingSenderId: '100007027162',
    projectId: 'doctify-9786a',
    storageBucket: 'doctify-9786a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeUkqd8X9BBC1F-UtihwhK0HJ7cCX5W2E',
    appId: '1:100007027162:web:2a3a981a18685b396a20e3',
    messagingSenderId: '100007027162',
    projectId: 'doctify-9786a',
    authDomain: 'doctify-9786a.firebaseapp.com',
    storageBucket: 'doctify-9786a.appspot.com',
  );
}
